package com.studup.backend.model.enums;

public enum NotificationType {
    NOUVEAU_MATCH,
    DEMANDE_ACCORD,
    ACCORD_ACCEPTE,
    ACCORD_REFUSE,
    NOUVEAU_MESSAGE,
    PAIEMENT_RECU,
    PAIEMENT_ECHOUE,
    CAUTION_RESTITUEE,
    AVIS_RECU,
    DOCUMENT_VALIDE,
    DOCUMENT_REFUSE,
    RAPPEL_DEPART,
    RAPPEL_ARRIVEE,
    SYSTEME
}
